#!/bin/bash
set -eu

SCRIPT_DIR=$( cd -- "$( dirname -- "$(readlink -f ${BASH_SOURCE[0]})" )" &> /dev/null && pwd )
PARENT_DIR=$(dirname "$SCRIPT_DIR")
OBJECTS="$PARENT_DIR/source/objects"
SUMMARY_FILE="$1"

echo "==> Checking for: toi files directories..."

# Check that every notebook has a matching directory of files
for item in $OBJECTS/toi_*.ipynb ; do
  name=$(basename -- "$item" .ipynb)
  dir="$OBJECTS/${name}_files"
  if [ ! -d $dir ]; then
    echo "ERROR: '${name}.ipynb' has no matching '${name}_files' directory  [$dir does not exist]"
    exit 1
  fi
done

echo "==> Checking for: $SUMMARY_FILE"
# Ensure the summary file exists
if [ ! -f "$SUMMARY_FILE" ]; then
  echo "ERROR: $SUMMARY_FILE does not exist."
  exit 1
fi

echo "==> Adding phase plots to _static ..."
cd source/_static/
for item in $(find ../objects -name 'phase_plot_TOI*.png'); do
  ln -fs $item .
done
cd - > /dev/null
