#!/bin/bash
set -eu

SCRIPT_DIR=$( cd -- "$( dirname -- "$(readlink -f ${BASH_SOURCE[0]})" )" &> /dev/null && pwd )
PARENT_DIR=$(dirname "$SCRIPT_DIR")

SRC_DIR="${PARENT_DIR}/source"
menu_page="${SRC_DIR}/menu_page.md"

# Render new page
new_page=$("${SCRIPT_DIR}/menu-page.py" "${SRC_DIR}")

echo "==> Checking menu page..."
# Only write to file if it differs from the existing page (or there is no existing page)
if [ ! -f "$menu_page" ] || ! echo "$new_page" | diff -q "$menu_page" - &> /dev/null ; then
  echo "==> Writing new $menu_page"
  echo "$new_page" > "$menu_page"
else
  echo "==> $menu_page has not changed"
fi
